dist: bionic
sudo: true
language: c++
compiler:
  - clang
addons:
  apt:
    packages:
      - libitpp-dev
      - libgtest-dev
      - cmake
script:
  - sudo sed -i '/^Defaults\tsecure_path.*$/ d' /etc/sudoers
  - sudo -E sh gtest_build.sh
  - cd givens_params && make && make test
