dist: bionic
sudo: true
language: c++
compiler:
  - clang
addons:
  apt:
    packages:
      - libitpp-dev
      - libgtest-dev
      - cmake
script:
  - sh gtest_build.sh
  - cd givens_params && make && make test
