dist: bionic
sudo: true
language: c++
compiler:
  - clang
addons:
  apt:
    packages:
      - libitpp-dev
      - libgtest-dev
      - cmake
script:
  - cd /usr/src/gtest && sudo -i cmake CMakeLists.txt && sudo -i make && sudo -i cp *.a /usr/lib && sudo -i ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a && sudo -i ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a && cd -
  - cd givens_params && make && make test
